import type { NextPage } from 'next'
import Head from 'next/head'

import { Center, Heading } from '@chakra-ui/layout'

const Home: NextPage = () => {
  return (
    <Center minH='100vh'>
      <Head>
        <title>Next Boilerplate - Chackra</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

        <Heading color='blueviolet'>Next Boilerplate - ChakraUI</Heading>
      </Center>
  )
}

export default Home
