import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function Page() {
  return <h1 className='text-3xl font-bold underline'>Hello, Next.js</h1>
}
